noun= input("Please type a person, place or thing: ")
body= input("Please type a part of the body: ")
adjective= input("Please type an adjective: ")
plural= input("Please type plural of a person, place or thing: ")
print("Before attacking an enemy {}, pirates armed themselves from head to {} with an {} arsenal of {}" .format(noun,body,adjective,plural))
plur2= input("Please type plural of a person, place or thing: ")
adj2= input("Please type an adjective: ")
verb= input("Please type an action word: ")
adj3= input("Please type an adjective: ")
body2= input("Please type a part of the body: ")
print("Their three favorite {} were: The Cutlass. Lightweight, {} -bladed, and easy to {} -it was used in {} quarters, often in hand-to-{} combat" .format(plur2, adj2,verb,adj3,body2))
noun2= input("Please type a person, place or thing: ")
plur3= input("Please type plural of a person, place or thing: ")
plur4= input("Please type plural of a person, place or thing: ")
adverb= input("Pleas type an adverb: ")
body3= input("Please type a part of the body: ")
print("The Pistol: Since a pistol could only fire a single {} without being reloaded, pirates often hid many loaded {} in the {} they were wearing and the pistol was the female pirates weapon of choice because it fit {} in the palm of her {}" .format(noun2,plur3,plur4,adverb,body3))
verb2= input("Please type an action word: ")
body4= input("Please type a body type, in plural form")
adj4= input("Please type an adjective: ")
noun3= input("Please type a person, place or thing: ")
num= input("Please type a number: ")
print("The Musket: Although it was very difficult to {} with gunpowder, a pirate with two good {} and a {} hand could hit a bull's- {} nine times out of {} with a musket" .format(verb2,body4,adj4,noun3,num))